Traceback (most recent call last):
  File "/home/hayashi/workspace/tbm-python/src/python/run.py", line 14, in <module>
    with open(dataset_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/hayashi/workspace/tbm-python/dataset/chess.dat.dat'
